7.1.2025, 21:11:19 - WARN - Operational Error: Error signing outJWTExpired: "exp" claim timestamp check failed | {"statusCode":500,"stack":"AppError: Error signing outJWTExpired: \"exp\" claim timestamp check failed\n    at Function.create (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\services\\Error.service.ts:58:12)\n    at C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:54:26\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:6:65)"}
7.1.2025, 21:11:19 - WARN - Operational Error: Error signing outJWTExpired: "exp" claim timestamp check failed | {"statusCode":500,"stack":"AppError: Error signing outJWTExpired: \"exp\" claim timestamp check failed\n    at Function.create (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\services\\Error.service.ts:58:12)\n    at C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:54:26\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:6:65)"}
7.1.2025, 21:12:12 - WARN - Operational Error: Error signing outJWTExpired: "exp" claim timestamp check failed | {"statusCode":500,"stack":"AppError: Error signing outJWTExpired: \"exp\" claim timestamp check failed\n    at Function.create (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\services\\Error.service.ts:58:12)\n    at C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:54:26\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:6:65)"}
7.1.2025, 21:12:12 - WARN - Operational Error: Error signing outJWTExpired: "exp" claim timestamp check failed | {"statusCode":500,"stack":"AppError: Error signing outJWTExpired: \"exp\" claim timestamp check failed\n    at Function.create (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\services\\Error.service.ts:58:12)\n    at C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:54:26\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\micha\\Desktop\\projects\\training-app\\backend\\src\\api\\auth\\auth.controller.ts:6:65)"}
